branding:
  color: black
  icon: triangle
description: 'Receive the deployment preview URL from Vercel'
inputs:
  vercel_project_id:
    description: 'Vercel project id'
    required: false
  vercel_team_id:
    description: 'Vercel team id'
    required: false
  vercel_app:
    description: 'Vercel app name'
    required: false
  vercel_from:
    description: 'Vercel deployment source'
    required: false
  vercel_limit:
    description: 'Vercel deployment limit'
    required: false
  vercel_since:
    description: 'Vercel deployment since'
    required: false
  vercel_state:
    description: 'Vercel deployment state'
    required: false
  vercel_target:
    description: 'Vercel deployment target'
    required: false
  vercel_to:
    description: 'Vercel deployment to'
    required: false
  vercel_until:
    description: 'Vercel deployment until'
    required: false
  vercel_users:
    description: 'Vercel deployment users'
    required: false
name: Vercel Preview URL
outputs:
  deployment_state:
    description: 'A string with the current deployment state, it could be one of the following QUEUED, BUILDING, READY, or ERROR.'
  preview_url:
    description: "A string with the unique URL of the deployment. If it hasn't finished uploading (is incomplete), the value will be null."
runs:
  main: dist/index.js
  using: node20
